[build]
  command = "npm run build"
  publish = "build/client"

[functions]
  directory = "build/server"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/remix-server"
  status = 200

[dev]
  command = "npm run dev"

# Environment variables (set these in Netlify Dashboard)
# SHOPIFY_API_KEY
# SHOPIFY_API_SECRET  
# DATABASE_URL
# SESSION_SECRET
# SHOPIFY_APP_URL
# SCOPES