[build]
  command = "npm run build"
  publish = "build/client"

[dev]
  command = "npm run dev"
  framework = "vite"

# Environment variables (set these in Netlify Dashboard)
# SHOPIFY_API_KEY
# SHOPIFY_API_SECRET  
# DATABASE_URL
# SESSION_SECRET
# SHOPIFY_APP_URL
# SCOPES