[build]
  command = "npm run build"
  publish = "build/client"

[dev]
  command = "npm run dev"
  framework = "vite"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors https://admin.shopify.com https://*.myshopify.com"

# Environment variables (set these in Netlify Dashboard)
# SHOPIFY_API_KEY
# SHOPIFY_API_SECRET  
# DATABASE_URL
# SESSION_SECRET
# SHOPIFY_APP_URL
# SCOPES