# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5c542354f25b7f53f8f87bed0457cc5d"
name = "nico-rewards"
handle = "nico-rewards"
application_url = "https://nico-rewards-2.netlify.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders"

[auth]
redirect_urls = ["https://nico-rewards-2.netlify.app/auth/callback", "https://nico-rewards-2.netlify.app/auth/shopify/callback", "https://nico-rewards-2.netlify.app/api/auth/callback"]

[pos]
embedded = false

[app_proxy]
url = "https://nico-rewards-2.netlify.app"
subpath = "proxy"
prefix = "apps"
